---
apiVersion: v1
kind: Namespace
metadata:
  labels: 
    istio-injection : enabled
  name: fdadi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdadi-medication-service
  namespace: fdadi
  labels:
    app: fdadi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdadi
  template:
    metadata:
      labels:
        app: fdadi
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: fdadi-medication-service
          image: clearavenuedocker/fdadi-medication-service:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /actuator/health
              port: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
          ports:
            - name: med-service
              containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: fdadi-medication-service
  namespace: fdadi
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: fdadi
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
spec:
  selector:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
