package com.clearavenue.fdadi.service;

import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

import com.clearavenue.fdadi.model.PharmClass;
import com.clearavenue.fdadi.repository.PharmClassRepository;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class PharmClassService {

    private final PharmClassRepository pharmRepo;

    public List<PharmClass> findAll() {
        return pharmRepo.findAll();
    }

    public Optional<PharmClass> findByMedicationName(final String pharmClassName) {
        return pharmRepo.findByPharmClassName(pharmClassName);
    }

    public void init() {
        pharmRepo.deleteAll();
        pharmRepo.save(PharmClass.builder().pharmClassName("5-alpha Reductase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("5-Lipoxygenase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Acetylcholine Release Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Acetylcholine Releasing Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Actinomycin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Adenosine Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Adrenal Steroid Synthesis Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Adrenergic Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Adrenocorticotropic Hormone [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aldehyde Dehydrogenase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aldosterone Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Alkylating Drug [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Allogeneic Cultured Cell Scaffold [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Allylamine Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("alpha-1 Adrenergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("alpha-Adrenergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("alpha-Adrenergic Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("alpha-Glucosidase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("alpha-Hydroxy Acid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aluminum Complex [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Amide Local Anesthetic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Amino Acid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Amino Acid Hypertonic Solution [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aminoglycoside Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aminoketone [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aminosalicylate [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Amphenicol-class Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Amphetamine Anorectic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Amylin Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Androgen [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Androgen Receptor Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Angiotensin 2 Receptor Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Angiotensin Converting Enzyme Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Anthracycline Topoisomerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Anti-anginal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antiarrhythmic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Anticholinergic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Anti-coagulant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antidiarrheal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antidote [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antidote for Acetaminophen Overdose [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antiemetic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Anti-epileptic Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antifibrinolytic Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antihelminthic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antihistamine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Anti-IgE [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antimalarial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antimetabolite [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antimetabolite Immunosuppressant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antimycobacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antiparasitic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antiprotozoal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antirheumatic Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antiseptic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Antivenin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aromatase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Aromatic Amino Acid Decarboxylation Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Arteriolar Vasodilator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Asparagine-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Atypical Antipsychotic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Autonomic Ganglionic Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Azole Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("B Lymphocyte Stimulator-specific Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Barbiturate [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Benzodiazepine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Benzodiazepine Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Benzothiazole [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Benzylamine Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("beta Lactamase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("beta2-Adrenergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("beta3-Adrenergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("beta-Adrenergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("beta-Adrenergic Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Biguanide [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Bile Acid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Bile Acid Sequestrant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Bismuth [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Blood Coagulation Factor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Blood Viscosity Reducer [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Bovine Intestinal Adenosine Deaminase [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Bradykinin B2 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Calcineurin Inhibitor Immunosuppressant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Calcitonin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Calcium [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Calcium Channel Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Calcium-sensing Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Calculi Dissolution Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cannabinoid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Carbamoyl Phosphate Synthetase 1 Activator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Carbonic Anhydrase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cardiac Glycoside [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Carnitine Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Catecholamine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Catecholamine Synthesis Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Catecholamine-depleting Sympatholytic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Catechol-O-Methyltransferase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("CCR5 Co-receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("CD20-directed Cytolytic Antibody [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("CD25-directed Cytotoxin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("CD3 Blocker Immunosuppressant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("CD52-directed Cytolytic Antibody [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cell Death Inducer [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Central alpha-2 Adrenergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Central Nervous System Stimulant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cephalosporin Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Chloride Channel Activator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholecystokinin Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholinergic Muscarinic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholinergic Muscarinic Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholinergic Nicotinic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholinergic Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholinesterase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cholinesterase Reactivator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Collagen-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Complement Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Contrast Agent for Ultrasound Imaging [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Copper-containing Intrauterine Device [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Corticosteroid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("CTLA-4-directed Blocking Antibody [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cysteine Depleting Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cytochrome P450 17A1 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cytochrome P450 2D6 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cytomegalovirus Nucleoside Analog DNA Polymerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Cytoprotective Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Decarboxylase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Demulcent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Depolarizing Neuromuscular Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Diagnostic Dye [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Diarylquinoline Antimycobacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dietary Cholesterol Absorption Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dihydrofolate Reductase Inhibitor Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dihydrofolate Reductase Inhibitor Antimalarial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dihydropyridine Calcium Channel Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dipeptidyl Peptidase 4 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Direct Thrombin Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dopamine-2 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Dopaminergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Echinocandin Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Endoglycosidase [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Epidermal Growth Factor Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Ergot Derivative [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Ergotamine Derivative [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Erythropoiesis-stimulating Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Ester Local Anesthetic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Estrogen [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Estrogen Agonist/Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Estrogen Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Factor VIII Activator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Factor Xa Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Folate Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Folate Analog Metabolic Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Gadolinium-based Contrast Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("gamma-Aminobutyric Acid A Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("gamma-Aminobutyric Acid-ergic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("General Anesthetic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Glinide [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("GLP-1 Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Glucosylceramide Synthase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Glycopeptide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Glycosaminoglycan [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Gonadotropin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Gonadotropin Releasing Hormone Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Gonadotropin Releasing Hormone Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Guanylate Cyclase-C Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hedgehog Pathway Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Helicobacter pylori Diagnostic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hematopoietic Stem Cell Mobilizer [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Heparin Reversal Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hepatitis B Virus Nucleoside Analog Reverse Transcriptase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hepatitis C Virus NS3/4A Protease Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hepatitis C Virus NS5A Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("HER2 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Herpes Simplex Virus Nucleoside Analog DNA Polymerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Herpes Zoster Virus Nucleoside Analog DNA Polymerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Herpesvirus Nucleoside Analog DNA Polymerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Histamine-1 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Histamine-1 Receptor Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Histamine-2 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Histone Deacetylase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("HMG-CoA Reductase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Blood Coagulation Factor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Immunodeficiency Virus 1 Non-Nucleoside Analog Reverse Transcriptase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Immunodeficiency Virus Integrase Strand Transfer Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Immunodeficiency Virus Nucleoside Analog Reverse Transcriptase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Immunoglobulin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Immunoglobulin G [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Platelet-derived Growth Factor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Human Serum Albumin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hydrolytic Lysosomal Glucocerebroside-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hydrolytic Lysosomal Glycogen-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hydrolytic Lysosomal Glycosaminoglycan-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hydrolytic Lysosomal Neutral Glycosphingolipid-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Hydroxyphenyl-Pyruvate Dioxygenase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Immunoglobulin G [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Influenza A M2 Protein Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Inhalation Diagnostic Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Insulin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Insulin Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Integrin Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Interferon alpha [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Interferon gamma [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Interleukin-1 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Interleukin-6 Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Interleukin-6 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Intestinal Lipase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Iron Chelator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Ketolide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Kinase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Lead Chelator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Leukocyte Growth Factor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Leukotriene Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Lincosamide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Lipid-based Polyene Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Lipopeptide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Live Attenuated Bacillus Calmette-Guerin Immunotherapy [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Live Attenuated Bacillus Calmette-Guerin Vaccine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Live Vaccinia Virus Vaccine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Local Anesthetic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Loop Diuretic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Low Molecular Weight Heparin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("l-Thyroxine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("l-Triiodothyronine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Lymphocyte Growth Factor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Macrolide [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Macrolide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Macrolide Antimicrobial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Mast Cell Stabilizer [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Melanin Synthesis Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Melatonin Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Metal Chelator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Methylated Sulfonamide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Methylating Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Methylxanthine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Microsomal Triglyceride Transfer Protein Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Microtubule Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Monoamine Oxidase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Monoamine Oxidase Type B Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Monobactam Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Mood Stabilizer [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("mTOR Inhibitor Immunosuppressant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Mucocutaneous Epithelial Cell Growth Factor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Mucolytic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Muscle Relaxant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Natriuretic Peptide [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Neuraminidase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nicotinic Acid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nitrate Vasodilator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nitrofuran Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nitrogen Binding Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nitroimidazole Antimicrobial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("N-methyl-D-aspartate Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Noncompetitive AMPA Glutamate Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nondepolarizing Neuromuscular Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nonergot Dopamine Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-narcotic Antitussive [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Animal Dander Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Animal Hair Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Animal Skin Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Chemical Allergen [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Feather Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Food Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Fungal Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized House Dust Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Insect Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Plant Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Plant Fiber Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Non-Standardized Pollen Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nonsteroidal Anti-inflammatory Drug [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Norepinephrine Reuptake Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("N-type Calcium Channel Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nucleoside Analog Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nucleoside Analog Antiviral [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Nucleoside Metabolic Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Omega-3 Fatty Acid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Opioid Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Opioid Agonist/Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Opioid Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Osmotic Diuretic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Osmotic Laxative [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Oxazolidinone Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Oxytocic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("P2Y12 Platelet Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Paramagnetic Contrast Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Parathyroid Hormone Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Parental Iron Replacement [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Parenteral Iron Replacement [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Partial Cholinergic Nicotinic Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Partial Opioid Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Partial Opioid Agonist/Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Pediculicide [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Penem Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Penicillin-class Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Peroxisome Proliferator Receptor alpha Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Peroxisome Proliferator Receptor gamma Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Phenothiazine [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Phenylalanine Hydroxylase Activator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Phosphate Binder [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Phosphodiesterase 3 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Phosphodiesterase 4 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Phosphodiesterase 5 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Photoactivated Radical Generator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Photoenhancer [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Plasma Volume Expander [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Platelet Aggregation Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Platelet-reducing Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Platinum-based Drug [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Pleuromutilin Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Polyene Antifungal [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Polyene Antimicrobial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Polymyxin-class Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Potassium Binder [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Potassium Channel Opener [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Potassium Salt [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Potassium-sparing Diuretic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Progesterone [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Progestin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Progestin Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Progestin-containing Intrauterine Device [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Prostacycline [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Prostacycline Vasodilator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Prostaglandin Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Prostaglandin E1 Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Prostaglandin E1 Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Protease Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Proteasome Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Proton Pump Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Provitamin D2 Compound [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Psoralen [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Purine Antimetabolite [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Pyrethroid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Pyrimidine Synthesis Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Pyrophosphate Analog DNA Polymerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Quinolone Antimicrobial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Radioactive Diagnostic Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Radioactive Diagnostic Agent for Positron Emission Tomography [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Radioactive Therapeutic Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Radiographic Contrast Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("RANK Ligand Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Recombinant Human Deoxyribonuclease 1 [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Recombinant Human Growth Hormone [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Recombinant Human Interferon beta [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Reducing and Complexing Thiol [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Renal Dehydropeptidase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Renin Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Respiratory Stimulant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Respiratory Syncytial Virus Anti-F Protein Monoclonal Antibody [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Retinoid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Rifamycin Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Rifamycin Antimycobacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("RNA Synthetase Inhibitor Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sclerosing Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Selective T Cell Costimulation Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Selective T Cell Costimulation Modulator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Serotonin and Norepinephrine Reuptake Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Serotonin Reuptake Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Serotonin-1b and Serotonin-1d Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Serotonin-2c Receptor Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Serotonin-3 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sigma-1 Agonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Skeletal Muscle Relaxant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Skin Test Antigen [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sodium-Glucose Cotransporter 2 Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Soluble Guanylate Cyclase Stimulator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Somatostatin Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sphingosine 1-phosphate Receptor Modulator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Animal Hair Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Animal Skin Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Chemical Allergen [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Insect Protein Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Insect Venom Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Insect Venom Protein Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Standardized Pollen Allergenic Extract [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Stimulant Laxative [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Streptogramin Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Substance P/Neurokinin-1 Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sucrose-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sulfonamide Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sulfonamide Antimicrobial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sulfone [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sulfonylurea [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Surfactant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sympathomimetic Amine Anorectic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Sympathomimetic-like Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tetracycline-class Antibacterial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tetracycline-class Antimicrobial [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tetracycline-class Drug [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thalidomide Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thiazide Diuretic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thiazide-like Diuretic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thiazolidinedione [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thrombopoiesis Stimulating Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thyroid Hormone Synthesis Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Thyroid Stimulating Hormone [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Topoisomerase Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tricyclic Antidepressant [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tuberculosis Skin Test [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tubulin Inhibiting Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Tumor Necrosis Factor Blocker [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Typical Antipsychotic [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Uncompetitive N-methyl-D-aspartate Receptor Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Unfractionated Heparin [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Urease Inhibitor [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Uric Acid-specific Enzyme [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vascular Endothelial Growth Factor-directed Antibody [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vasodilator [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vasopressin Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vasopressin Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vinca Alkaloid [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin A [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin B12 [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin D [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin D Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin D2 Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin D3 Analog [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin K [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Vitamin K Antagonist [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Warfarin Reversal Agent [EPC]").build());
        pharmRepo.save(PharmClass.builder().pharmClassName("Xanthine Oxidase Inhibitor [EPC]").build());
    }
}
